### ISSUE TITLE
Starting when server already started causes server error

### ISSUE THREAD

**Issue by jjcf89** [Ahtenus/minecraft-init#30]
If you run /etc/init.d/minecraft start when the server is already running causes an error message to appear in server.

This seems to be cause by the check_links function.  It seems to reset the links even if they are already setup and it does this even if the server is running which is bad.

I suppose the solution could be to either not change the links if they already exist or check for the server running much sooner.

I imagine to_ram() would have a similar issue.

**Comment by Ahtenus** [comment]
Thanks for pointing it out, should be fixed...

**Comment by jjcf89** [comment]
I don't see any fix.  The issue still occurs with latest script.

**Comment by Ahtenus** [comment]
I've have been busy...
What I meant was that I should fix it sometime.

**Comment by jjcf89** [comment]
Ahh ok no problem.

**Comment by Ahtenus** [comment]
Now it's fixed though ;)

**Comment by jjcf89** [comment]
Thanks
